### ISSUE TITLE
Is there an endpoint to cancel all open orders?

### ISSUE THREAD

**Issue by Jie-Cheng** [hyperliquid-dex/hyperliquid-rust-sdk#15]
You can cancel all open orders on the exchange GUI, but I don't see this endpoint in the documentation or the sdk.

Thank you!

**Comment by traderben** [comment]
There is no endpoint to do this. The frontend fetches all the open orders and cancels them one at a time

**Comment by Jie-Cheng** [comment]
Thanks for the clarification.
