### ISSUE TITLE
Add helper functions to open and close market/limit orders

### ISSUE THREAD

**Issue by Frixoe** [hyperliquid-dex/hyperliquid-rust-sdk#44]
This should help abstract away the need to know how to create the correct the order and also handle all the errors

**Comment by spacecadet-jap** [comment]
I can submit a PR for this as I've already implemented it by setting a limit order that aggresses the book

**Comment by Frixoe** [comment]
> I can submit a PR for this as I've already implemented it by setting a limit order that aggresses the book. Just let me know if you would like me to submit it.

Yeah sure, go for it. I'll go through and let you know what I think.

**Comment by spacecadet-jap** [comment]
I'll submit a PR over the weekend

**Comment by spacecadet-jap** [comment]
I submitted PR #54 to create a market order. It would be nice to not include the current mid price but I don't want to create a latency-heavy call to get it if clients are already tracking it. I added it as a seperate function so you can easily incorporate it into the API as I don't want to break anything upstream.

**Comment by mathdroid** [comment]
Submitted PR #55 @Frixoe

**Comment by mathdroid** [comment]
when will the changes gets merged to the crate? @Frixoe @lmlmt

<img width="531" alt="Screenshot 2024-09-09 at 14 35 27" src="https://github.com/user-attachments/assets/429332eb-1f43-42b5-afc2-69e20f915f0d">
