### ISSUE TITLE
If WsManager is dropped, the spawned tokio tasks aren't stopped

### ISSUE THREAD

**Issue by Frixoe** [hyperliquid-dex/hyperliquid-rust-sdk#47]
This is an issue because if WsManager is stopped, the two tokio tasks are still running in the background which could cause performance issues and certainly populates logs.

**Comment by abrkn** [comment]
i'm facing this issue as well

**Comment by Frixoe** [comment]
Yeah, I've created a fix, waiting for my previous PR to be merged so I can open a PR for that.
